import { readLocal } from './storage.js?v=storage-v1';
import { LANGUAGES, preferredLanguage } from '../application/language-policy.js';

export { LANGUAGES, preferredLanguage } from '../application/language-policy.js';

export const COPY = {
  pt: {
    tagline: 'Exercícios, Prática & Técnica', homeTagline: 'Três problemas do Codeforces por dia. Basta resolver um.', homeTaglineFirst: 'Três problemas do Codeforces por dia.', homeTaglineSecondBefore: 'Basta resolver ', homeTaglineEmphasis: 'um', homeTodayKicker: 'Desafio diário', homeTodayTitle: 'Desafio diário', homeTodayAction: 'Praticar', homeChallengesAction: 'Desafios anteriores', homeNewHere: 'Novo por aqui?', homeSettings: 'Configurações', taglineLine1: 'Exercícios,', taglineLine2: 'Prática &', taglineLine3: 'Técnica', intro: 'Três problemas do Codeforces por dia. É só fazer um.', introLine1: 'Três problemas do Codeforces por dia.', introLine2Before: 'É só fazer ', introLine2Emphasis: 'um', homeNav: 'Início', primaryNavigation: 'Navegação principal', dailyNav: 'Hoje', challengesNav: 'Anteriores', homeHeading: 'Prática diária de programação', homeLead: 'Escolha um nível, receba três problemas e resolva um.', homeStartHeading: 'Por onde começar?', homeDailyHeading: 'Desafio de hoje', historicalChallenge: 'Desafio histórico', homeDailyText: 'Veja os problemas selecionados para a data atual.', homeDailyLink: 'Ir para o treino de hoje', homeChallengesHeading: 'Desafios anteriores', homeChallengesText: 'Consulte o histórico e retorne a qualquer desafio disponível.', homeChallengesLink: 'Abrir histórico', homeHowHeading: 'Como funciona', homeHowText: 'Os enunciados e envios ficam no Codeforces. O ACCEPT organiza uma prática curta e progressiva.', howToLink: 'Como usar?', footerPages: 'Páginas adicionais', howToTitle: 'Como usar o ACCEPT?', howToHeading: 'Como usar o ACCEPT?', howToCodeforcesBefore: 'O ', howToCodeforcesAfter: ' contém os enunciados, os envios e os resultados.', howToStep2Title: 'Enunciado do problema', howToStep2Before: 'Abra o enunciado pelo título no ', howToStep2After: '.', howToStep2Item2: 'Se precisar, use a tradução do navegador ou outra ferramenta.', howToStep3Title: 'Solução e envio', howToStep3Item1: 'Resolva o problema e envie a solução no Codeforces.', howToStep3Item2: 'Uma conta gratuita é necessária para acompanhar o resultado.', howToStep4Title: 'Handle do Codeforces', howToStep4Item1: 'Informe seu handle do Codeforces ao voltar ao treino.', howToStep4Item2: 'Os resultados dos envios aparecem na lista.', howToNote: 'Você pode ler e praticar sem uma conta. Uma conta é necessária para enviar soluções e acompanhar resultados.', previous: 'Calendário', weekPrev: 'semana anterior', weekNext: 'próxima semana',
    loading: 'Carregando problemas...', retry: 'Tentar novamente', unavailable: 'Não foi possível carregar problemas agora.', historicalUnavailable: 'Não foi possível carregar os problemas desta data.', empty: 'Ainda não há problemas para este nível.',
    handle: 'Seu handle (ex.: tourist)…', recentHandles: 'Handles recentes', clearRecentHandles: 'Limpar handles recentes', ratingLabel: 'rating', ratingPlaceholder: '—', unrated: 'unrated', use: 'Carregar handle do Codeforces', refresh: 'Atualizar dados do Codeforces', syncLoading: 'Carregando dados...', syncRefreshing: 'Atualizando dados...', selectingRecommendedLevel: 'Selecionando nível recomendado...', accountDataError: 'Não foi possível carregar os dados', dataUnavailable: 'Não foi possível atualizar os envios.', completionDone: '✓ Feito!', statusUnavailable: 'Não foi possível atualizar os envios.',
    acceptedOnDate: 'Aceito nesta data', unsuccessfulOnDate: 'Tentativa sem Accepted nesta data', unsuccessfulOtherDate: 'Tentativa sem Accepted em outra data', shareChallenge: 'Compartilhar', shareText: 'Tente este desafio do ACCEPT:', shareShared: 'Desafio compartilhado.', shareCopied: 'Copiado!', shareFailed: 'Erro ao compartilhar', solved: 'Resolvidos', dayAcRecorded: 'AC registrado neste dia', dayNoRecordedAc: 'Nenhum AC registrado neste dia', levelScrollHint: 'Deslize para ver mais níveis.', externalLinkHint: 'abre em nova aba', dayCompleted: 'Concluído neste dia', dayNotCompleted: 'Não concluído neste dia',
    problemHeaderDifficulty: 'Dificuldade', problemHeaderDifficultyShort: 'Rating', problemHeaderProblem: 'Problema', problemHeaderId: 'ID', problemHeaderDone: 'Feito?', problemTable: 'Problemas do treino', language: 'Idioma', languageCurrent: 'Mudar idioma. Idioma atual: Português.', theme: 'Tema', themeCurrent: 'Tema: Sistema', themeLight: 'Claro', themeSystem: 'Sistema', themeDark: 'Escuro', rank: 'nível', expertBucket: 'Expert e Candidate Master', legend: 'legend', selected: 'selecionado', accepted: 'Aceito', all: 'Todos',
    future: 'em breve', calendarUnavailableNote: 'Dias futuros e dias anteriores ao início do ACCEPT não estão disponíveis.', calendarCompletedLegend: '✓ Resolvido', unavailableDate: 'indisponível', openChallenge: 'abrir desafio', back: '← Voltar ao treino', monthPrev: 'mês anterior', monthNext: 'próximo mês', noHandle: 'Adicione um handle para verificar.', handleLabel: 'Digite um handle do Codeforces...', loadHandle: 'Carregar', goForIt: 'Bora!', help: 'Ajuda', helpHeading: 'Como usar o desafio de hoje', helpStep1: 'Escolha um nível. O ACCEPT mostra três problemas.', helpStep2: 'Abra o enunciado pelo título no Codeforces. Se precisar, use a tradução do navegador.', helpStep3: 'Resolva o problema e envie sua solução no Codeforces.', helpStep4: 'Informe seu handle do Codeforces se quiser que o ACCEPT confira seus envios.', helpStep5: 'Quando o Codeforces marcar sua solução como Accepted, o ACCEPT marcará o problema como concluído.', helpNote: 'Você pode ler e praticar sem uma conta. É preciso ter uma conta gratuita no Codeforces para enviar soluções e acompanhar resultados. O ACCEPT nunca precisa da sua senha.', close: 'Fechar',
    apiError: 'Codeforces não respondeu. Tente novamente.', handleNotFound: 'Handle não encontrado. Confira a grafia e tente novamente.', current: 'Hoje', calendar: 'Calendário', calendarTitle: 'ACCEPT Coding Club: Calendário', challengesHeading: 'Desafios anteriores', challengesLead: 'Escolha um dia para abrir o desafio.', yearPrev: 'ano anterior', yearNext: 'ano seguinte', todayTraining: 'Treino de hoje', recentDays: 'Dias recentes', level: 'Nível', account: 'Conta Codeforces', gameTitle: 'Treino diário', todayTitle: 'ACCEPT Coding Club: Treino de hoje',
  },
  en: {
    tagline: 'Everyday Practice & Training', homeTagline: 'Three Codeforces problems each day. Solve one.', homeTaglineFirst: 'Three Codeforces problems each day.', homeTaglineSecondBefore: 'Solve ', homeTaglineEmphasis: 'one', homeTodayKicker: 'Daily challenge', homeTodayTitle: 'Daily challenge', homeTodayAction: 'Practice', homeChallengesAction: 'Previous challenges', homeNewHere: 'New here?', homeSettings: 'Settings', taglineLine1: 'Everyday', taglineLine2: 'Practice &', taglineLine3: 'Training', intro: 'Three Codeforces problems each day. Just solve one.', introLine1: 'Three Codeforces problems each day.', introLine2Before: 'Just solve ', introLine2Emphasis: 'one', homeNav: 'Home', primaryNavigation: 'Primary navigation', dailyNav: 'Today', challengesNav: 'Previous', homeHeading: 'Daily programming practice', homeLead: 'Choose a level, get three problems, and solve one.', homeStartHeading: 'Where should I start?', homeDailyHeading: "Today's challenge", historicalChallenge: 'Historical challenge', homeDailyText: 'See the problems selected for today.', homeDailyLink: "Go to today's training", homeChallengesHeading: 'Previous challenges', homeChallengesText: 'Browse the history and return to any available challenge.', homeChallengesLink: 'Open history', homeHowHeading: 'How it works', homeHowText: 'Statements and submissions live on Codeforces. ACCEPT organizes short, progressive practice.', howToLink: 'How to use?', footerPages: 'Additional pages', howToTitle: 'How to use ACCEPT?', howToHeading: 'How to use ACCEPT?', howToCodeforcesBefore: '', howToCodeforcesAfter: ' contains the statements, submissions, and results.', howToStep2Title: 'Problem statement', howToStep2Before: 'Open the statement through its title on ', howToStep2After: '.', howToStep2Item2: 'If needed, use browser translation or another tool.', howToStep3Title: 'Solution and submission', howToStep3Item1: 'Solve the problem and submit on Codeforces.', howToStep3Item2: 'A free account is required to track the result.', howToStep4Title: 'Codeforces handle', howToStep4Item1: 'Enter your Codeforces handle when you return.', howToStep4Item2: 'Submission results appear in the list.', howToNote: 'You can read and practice without an account. An account is required to submit solutions and track results.', flowStart: 'Choose a problem', flowSubmit: 'Submit your solution', flowVerdict: 'Read the verdict', previous: 'Calendar', archiveLegend: 'Calendar legend', legendToday: 'Today', legendAvailable: 'Available', legendDone: 'Accepted confirmed', weekPrev: 'previous week', weekNext: 'next week',
    loading: 'Loading problems...', retry: 'Try again', unavailable: 'Problems could not be loaded right now.', historicalUnavailable: 'Could not load problems for this date.', empty: 'There are no problems for this level yet.',
    handle: 'Your handle (e.g. tourist)…', handleHelp: 'Optional: use your handle to track your Accepted submissions.', recentHandles: 'Recent handles', clearRecentHandles: 'Clear recent handles', ratingLabel: 'rating', ratingPlaceholder: '—', unrated: 'unrated', use: 'Load Codeforces handle', refresh: 'Refresh Codeforces data', syncLoading: 'Loading data...', syncRefreshing: 'Refreshing data...', selectingRecommendedLevel: 'Selecting recommended level...', accountDataError: 'Could not load the data', dataUnavailable: 'Could not refresh submissions.', completionDone: '✓ Done!', statusUnavailable: 'Could not refresh submissions.',
    acceptedOnDate: 'Accepted on this date', unsuccessfulOnDate: 'Unsuccessful attempt on this date', unsuccessfulOtherDate: 'Unsuccessful attempt on another date', shareChallenge: 'Share', shareText: 'Try this ACCEPT challenge:', shareShared: 'Challenge shared.', shareCopied: 'Copied!', shareFailed: 'Share failed', solved: 'Solved', dayAcRecorded: 'AC recorded on this day', dayNoRecordedAc: 'No AC recorded on this day', levelScrollHint: 'Swipe to see more levels.', externalLinkHint: 'opens in a new tab', dayCompleted: 'Completed on this day', dayNotCompleted: 'Not completed on this day',
    problemHeaderDifficulty: 'Codeforces rating', problemHeaderDifficultyShort: 'Rating', problemHeaderProblem: 'Problem', problemHeaderId: 'ID', problemHeaderDone: 'Done?', problemTable: 'Training problems', language: 'Language', languageCurrent: 'Change language. Current language: English.', theme: 'Theme', themeCurrent: 'Theme: System', themeLight: 'Light', themeSystem: 'System', themeDark: 'Dark', rank: 'rank', expertBucket: 'Expert and Candidate Master', legend: 'legend', selected: 'selected', accepted: 'Accepted', all: 'All',
    future: 'soon', calendarUnavailableNote: 'Future days and days before ACCEPT launched are unavailable.', calendarCompletedLegend: '✓ Completed', unavailableDate: 'unavailable', openChallenge: 'open challenge', back: '← Back to training', monthPrev: 'previous month', monthNext: 'next month', noHandle: 'Add a handle to check.', handleLabel: 'Enter a Codeforces handle...', loadHandle: 'Load', goForIt: 'Go for it!', help: 'Help', helpHeading: 'How to use today’s challenge', helpStep1: 'Choose a level. ACCEPT shows three problems.', helpStep2: 'Open the problem statement through its title on Codeforces. Use browser translation if needed.', helpStep3: 'Solve the problem and submit your solution on Codeforces.', helpStep4: 'Enter your Codeforces handle if you want ACCEPT to check your submissions.', helpStep5: 'When Codeforces marks your solution “Accepted”, ACCEPT marks the problem as complete.', helpNote: 'You can read and practise without an account. A free Codeforces account is needed to submit solutions and track results. ACCEPT never needs your password.', close: 'Close',
    apiError: 'Codeforces did not respond. Try again.', handleNotFound: 'Handle not found. Check the spelling and try again.', current: 'Today', calendar: 'Calendar', calendarTitle: 'ACCEPT Coding Club: Calendar', challengesHeading: 'Previous challenges', challengesLead: 'Choose a day to open its challenge.', yearPrev: 'previous year', yearNext: 'next year', todayTraining: "Today's training", recentDays: 'Recent days', level: 'Level', account: 'Codeforces account', gameTitle: "Today's training", todayTitle: "ACCEPT Coding Club: Today's training",
  },
  es: {
    tagline: 'Ejercicios, Práctica y Técnica', homeTagline: 'Tres problemas de Codeforces al día. Resuelve uno.', homeTaglineFirst: 'Tres problemas de Codeforces al día.', homeTaglineSecondBefore: 'Resuelve ', homeTaglineEmphasis: 'uno', homeTodayKicker: 'Desafío diario', homeTodayTitle: 'Desafío diario', homeTodayAction: 'Practicar', homeChallengesAction: 'Desafíos anteriores', homeNewHere: '¿Nuevo por aquí?', homeSettings: 'Configuración', taglineLine1: 'Ejercicios,', taglineLine2: 'Práctica y', taglineLine3: 'Técnica', intro: 'Tres problemas de Codeforces al día. Solo tienes que resolver uno.', introLine1: 'Tres problemas de Codeforces al día.', introLine2Before: 'Solo tienes que resolver ', introLine2Emphasis: 'uno', homeNav: 'Inicio', primaryNavigation: 'Navegación principal', dailyNav: 'Hoy', challengesNav: 'Anteriores', homeHeading: 'Práctica diaria de programación', homeLead: 'Elige un nivel, recibe tres problemas y resuelve uno.', homeStartHeading: '¿Por dónde empezar?', homeDailyHeading: 'Desafío de hoy', historicalChallenge: 'Desafío histórico', homeDailyText: 'Consulta los problemas seleccionados para hoy.', homeDailyLink: 'Ir al entrenamiento de hoy', homeChallengesHeading: 'Desafíos anteriores', homeChallengesText: 'Consulta el historial y vuelve a cualquier desafío disponible.', homeChallengesLink: 'Abrir historial', homeHowHeading: 'Cómo funciona', homeHowText: 'Los enunciados y envíos están en Codeforces. ACCEPT organiza una práctica breve y progresiva.', howToLink: '¿Cómo usarlo?', footerPages: 'Páginas adicionales', howToTitle: '¿Cómo usar ACCEPT?', howToHeading: '¿Cómo usar ACCEPT?', howToCodeforcesBefore: '', howToCodeforcesAfter: ' contiene los enunciados, los envíos y los resultados.', howToStep2Title: 'Enunciado del problema', howToStep2Before: 'Abre el enunciado desde su título en ', howToStep2After: '.', howToStep2Item2: 'Si hace falta, usa la traducción del navegador u otra herramienta.', howToStep3Title: 'Solución y envío', howToStep3Item1: 'Resuelve el problema y envía la solución en Codeforces.', howToStep3Item2: 'Se necesita una cuenta gratuita para seguir el resultado.', howToStep4Title: 'Handle de Codeforces', howToStep4Item1: 'Indica tu handle de Codeforces al volver.', howToStep4Item2: 'Los resultados de los envíos aparecen en la lista.', howToNote: 'Puedes leer y practicar sin una cuenta. Se necesita una cuenta para enviar soluciones y seguir los resultados.', previous: 'Calendario', weekPrev: 'semana anterior', weekNext: 'semana siguiente',
    loading: 'Cargando problemas...', retry: 'Intentar de nuevo', unavailable: 'No se pudieron cargar problemas ahora.', historicalUnavailable: 'No se pudieron cargar los problemas de esta fecha.', empty: 'Todavía no hay problemas para este nivel.',
    handle: 'Tu handle (p. ej., tourist)…', handleHelp: 'Opcional: usa tu handle para seguir tus Accepted.', recentHandles: 'Handles recientes', clearRecentHandles: 'Limpiar handles recientes', ratingLabel: 'rating', ratingPlaceholder: '—', unrated: 'unrated', use: 'Cargar handle de Codeforces', refresh: 'Actualizar datos de Codeforces', syncLoading: 'Cargando datos...', syncRefreshing: 'Actualizando datos...', selectingRecommendedLevel: 'Seleccionando nivel recomendado...', accountDataError: 'No se pudieron cargar los datos', dataUnavailable: 'No se pudieron actualizar los envíos.', completionDone: '✓ ¡Listo!', statusUnavailable: 'No se pudieron actualizar los envíos.',
    acceptedOnDate: 'Aceptado en esta fecha', unsuccessfulOnDate: 'Intento sin Accepted en esta fecha', acceptedOtherDate: 'Aceptado en otra fecha', unsuccessfulOtherDate: 'Intento sin Accepted en otra fecha', shareChallenge: 'Compartir', shareText: 'Prueba este desafío de ACCEPT:', shareShared: 'Desafío compartido.', shareCopied: '¡Copiado!', shareFailed: 'Error al compartir', solved: 'Resueltos', dayAcRecorded: 'AC registrado este día', dayNoRecordedAc: 'Sin AC registrado este día', levelScrollHint: 'Desliza para ver más niveles.', externalLinkHint: 'abre en una pestaña nueva', dayCompleted: 'Completado este día', dayNotCompleted: 'No completado este día',
    problemHeaderDifficulty: 'Dificultad', problemHeaderDifficultyShort: 'Rating', problemHeaderProblem: 'Problema', problemHeaderId: 'ID', problemHeaderDone: '¿Listo?', problemTable: 'Problemas del entrenamiento', language: 'Idioma', languageCurrent: 'Cambiar idioma. Idioma actual: Español.', theme: 'Tema', themeCurrent: 'Tema: Sistema', themeLight: 'Claro', themeSystem: 'Sistema', themeDark: 'Oscuro', rank: 'rango', expertBucket: 'Expert y Candidate Master', legend: 'legend', selected: 'seleccionado', accepted: 'Aceptado', all: 'Todos',
    future: 'pronto', calendarUnavailableNote: 'Los días futuros y los días anteriores al inicio de ACCEPT no están disponibles.', calendarCompletedLegend: '✓ Completado', unavailableDate: 'no disponible', openChallenge: 'abrir desafío', back: '← Volver al entrenamiento', monthPrev: 'mes anterior', monthNext: 'mes siguiente', noHandle: 'Añade un handle para verificar.', handleLabel: 'Escribe un handle de Codeforces...', loadHandle: 'Cargar', goForIt: '¡Dale!', help: 'Ayuda', helpHeading: 'Cómo usar el desafío de hoy', helpStep1: 'Elige un nivel. ACCEPT muestra tres problemas.', helpStep2: 'Abre el enunciado desde su título en Codeforces. Si hace falta, usa la traducción del navegador.', helpStep3: 'Resuelve el problema y envía tu solución en Codeforces.', helpStep4: 'Indica tu handle de Codeforces si quieres que ACCEPT compruebe tus envíos.', helpStep5: 'Cuando Codeforces marque tu solución como «Accepted», ACCEPT marcará el problema como completado.', helpNote: 'Puedes leer y practicar sin una cuenta. Necesitas una cuenta gratuita de Codeforces para enviar soluciones y seguir los resultados. ACCEPT nunca necesita tu contraseña.', close: 'Cerrar',
    apiError: 'Codeforces no respondió. Inténtalo de nuevo.', handleNotFound: 'No se encontró el handle. Comprueba la escritura e inténtalo de nuevo.', current: 'Hoy', calendar: 'Calendario', calendarTitle: 'ACCEPT Coding Club: Calendario', challengesHeading: 'Desafíos anteriores', challengesLead: 'Elige un día para abrir el desafío.', yearPrev: 'año anterior', yearNext: 'año siguiente', todayTraining: 'Entrenamiento de hoy', recentDays: 'Días recientes', level: 'Nivel', account: 'Cuenta de Codeforces', gameTitle: 'Entrenamiento de hoy', todayTitle: 'ACCEPT Coding Club: Entrenamiento de hoy',
  },
};

export function languageFromPreferences(saved, primary) {
  return LANGUAGES.includes(saved) ? saved : preferredLanguage(primary);
}
export function getLanguage() {
  const routeLanguage = globalThis.location?.pathname?.match(/^\/(pt|en|es)(?:\/|$)/)?.[1];
  const saved = readLocal('accept-language');
  const primary = globalThis.navigator?.languages?.[0] || globalThis.navigator?.language || '';
  return languageFromPreferences(routeLanguage || saved, primary);
}
export function text(key) { return COPY[getLanguage()][key] ?? key; }
